-- =============================================================================
-- ABYSS: KHAOS DESCENT — Phase 3a world navigation schema
-- =============================================================================
-- Adds the primitives needed for room-by-room exploration:
--   * `rooms` — both shared (hand-designed tutorial floors) and personal
--     (procedural per-character floors, populated from Phase 4 onward).
--   * `room_connections` — directed adjacency graph (from + direction → to).
--   * `room_npcs` — pivot of which NPCs occupy which room.
--   * `npc_dialogues` + `npc_dialogue_lines` — branching scripted dialogue.
--   * `character_room_visits` — per-character "fog of war" tracking.
--   * `npcs.portrait_url` — generated by PixelLab (per docs/ASSET_PIPELINE.md).
-- =============================================================================

alter table public.npcs
    add column if not exists portrait_url text;

-- -----------------------------------------------------------------------------
-- rooms: shared rooms (character_id IS NULL) for hand-designed tutorial /
-- hub floors; personal rooms (character_id set) for the per-character
-- procedural abyss starting floor 99 in Phase 4.
-- -----------------------------------------------------------------------------

create table if not exists public.rooms (
    id                  uuid primary key default gen_random_uuid(),
    floor_number        integer not null references public.floors(floor_number) on delete restrict,
    character_id        uuid references public.characters(id) on delete cascade,
    room_index          integer not null,
    name                text not null,
    description         text,
    room_type           text not null check (room_type in (
        'hub','tutorial','mob','sleeping','empty','item','npc','boss','exit'
    )),
    is_safe             boolean not null default false,
    biome_id            text references public.biomes(id) on delete restrict,
    seed                bigint,
    created_at          timestamptz not null default now(),
    updated_at          timestamptz not null default now()
);

create index if not exists rooms_floor_idx on public.rooms (floor_number);
create index if not exists rooms_character_idx on public.rooms (character_id);

-- Shared rooms (tutorial / hub) are unique by (floor_number, room_index) when
-- character_id IS NULL. Personal rooms can repeat across players.
create unique index if not exists rooms_shared_unique
    on public.rooms (floor_number, room_index)
    where character_id is null;
create unique index if not exists rooms_personal_unique
    on public.rooms (character_id, floor_number, room_index)
    where character_id is not null;

-- -----------------------------------------------------------------------------
-- room_connections: directed graph. (from_room, direction) → to_room.
-- The reverse edge is stored explicitly (cleaner than one-way symmetry).
-- -----------------------------------------------------------------------------

create table if not exists public.room_connections (
    from_room_id        uuid not null references public.rooms(id) on delete cascade,
    direction           text not null check (direction in ('north','south','east','west')),
    to_room_id          uuid not null references public.rooms(id) on delete cascade,
    is_locked           boolean not null default false,
    unlock_requirement  text,
    primary key (from_room_id, direction),
    constraint room_connections_no_self_loop check (from_room_id <> to_room_id)
);

create index if not exists room_connections_to_idx on public.room_connections (to_room_id);

-- -----------------------------------------------------------------------------
-- room_npcs: which NPCs stand in which room. Phase 3a uses this for Cedric.
-- -----------------------------------------------------------------------------

create table if not exists public.room_npcs (
    room_id     uuid not null references public.rooms(id) on delete cascade,
    npc_id      text not null references public.npcs(id) on delete cascade,
    primary key (room_id, npc_id)
);

create index if not exists room_npcs_npc_idx on public.room_npcs (npc_id);

-- -----------------------------------------------------------------------------
-- Dialogue: an NPC has multiple `npc_dialogues` (e.g. 'first_meet', 'returning').
-- Each dialogue is a sequence of `npc_dialogue_lines`. Translations live in
-- `translations` keyed by entity_type='npc_dialogue_line' + entity_id=line.id.
-- -----------------------------------------------------------------------------

create table if not exists public.npc_dialogues (
    id                  uuid primary key default gen_random_uuid(),
    npc_id              text not null references public.npcs(id) on delete cascade,
    dialogue_key        text not null,
    is_default_first    boolean not null default false,
    created_at          timestamptz not null default now(),
    updated_at          timestamptz not null default now(),
    constraint npc_dialogues_unique_key unique (npc_id, dialogue_key)
);

create index if not exists npc_dialogues_npc_idx on public.npc_dialogues (npc_id);
-- One default-first dialogue per NPC.
create unique index if not exists npc_dialogues_one_default_first
    on public.npc_dialogues (npc_id) where is_default_first;

create table if not exists public.npc_dialogue_lines (
    id                  uuid primary key default gen_random_uuid(),
    dialogue_id         uuid not null references public.npc_dialogues(id) on delete cascade,
    sequence_index      integer not null,
    speaker             text not null default 'npc' check (speaker in ('npc','narrator','choice')),
    text                text not null,
    created_at          timestamptz not null default now(),
    updated_at          timestamptz not null default now(),
    constraint npc_dialogue_lines_seq_unique unique (dialogue_id, sequence_index)
);

create index if not exists npc_dialogue_lines_dialogue_idx
    on public.npc_dialogue_lines (dialogue_id, sequence_index);

-- -----------------------------------------------------------------------------
-- character_room_visits: which rooms the character has stepped into. Powers
-- the minimap fog-of-war and "first_meet" dialogue triggers.
-- -----------------------------------------------------------------------------

create table if not exists public.character_room_visits (
    character_id        uuid not null references public.characters(id) on delete cascade,
    room_id             uuid not null references public.rooms(id) on delete cascade,
    first_visited_at    timestamptz not null default now(),
    last_visited_at     timestamptz not null default now(),
    primary key (character_id, room_id)
);

create index if not exists character_room_visits_room_idx
    on public.character_room_visits (room_id);

-- -----------------------------------------------------------------------------
-- character_npc_meets: which NPCs the character has spoken to (so we can
-- branch dialogue between first-meet and returning). One row per
-- (character_id, npc_id) the first time they speak.
-- -----------------------------------------------------------------------------

create table if not exists public.character_npc_meets (
    character_id        uuid not null references public.characters(id) on delete cascade,
    npc_id              text not null references public.npcs(id) on delete cascade,
    first_met_at        timestamptz not null default now(),
    primary key (character_id, npc_id)
);

-- -----------------------------------------------------------------------------
-- characters.current_room_id was already declared in Phase 2; add the FK now
-- that rooms exists.
-- -----------------------------------------------------------------------------

do $$
begin
    if not exists (
        select 1 from information_schema.referential_constraints
        where constraint_name = 'characters_current_room_id_fkey'
    ) then
        alter table public.characters
            add constraint characters_current_room_id_fkey
            foreign key (current_room_id) references public.rooms(id) on delete set null;
    end if;
end $$;

-- -----------------------------------------------------------------------------
-- Lockdown
-- -----------------------------------------------------------------------------

select public.lockdown_table('public.rooms');
select public.lockdown_table('public.room_connections');
select public.lockdown_table('public.room_npcs');
select public.lockdown_table('public.npc_dialogues');
select public.lockdown_table('public.npc_dialogue_lines');
select public.lockdown_table('public.character_room_visits');
select public.lockdown_table('public.character_npc_meets');
